employees/urls.py
from django.conf.urls import url

from . import views

pk = r'(?P<pk>\d+)'

urlpatterns = [
    # employee list
    url(r'^$',                                views.EmployeeList.as_view(),         name='employees'),
    url(r'^new$',                             views.EmployeeCreate.as_view(),       name='employee_new'),
    url(r'^new/emailverify/$',                views.ajax_verify_email,              name='emailverify'),
    url(r'^autocomplete/$',                   views.ajax_autocomplete,              name='autocomplete'),
    url(r'^' + pk + r'$',                     views.EmployeeDetail.as_view(),       name='employee_detail'),
    url(r'^' + pk + r'/new_month$',           views.MonthCreate.as_view(),          name='month_new'),
    url(r'^edit/'       + pk + r'$',          views.EmployeeUpdate.as_view(),       name='employee_edit'),
    url(r'^months/'     + pk + r'$',          views.MonthUpdate.as_view(),          name='month_edit'),
    url(r'^delete/'     + pk + r'$',          views.EmployeeDelete.as_view(),       name='employee_delete'),
    url(r'^del_month/'  + pk + r'$',          views.MonthDelete.as_view(),          name='month_delete'),
    url(r'^appr_month/' + pk + r'/$',         views.MonthApprove.as_view(),         name='month_approve'),
    url(r'^appr_NOT_month/' + pk + r'/$',     views.Month_NOT_Approve.as_view(),    name='month_NOT_approve'),
    url(r'^employee_message/' + pk,           views.EmployeeMessage.as_view(),      name='employee_message'),
    url(r'^dateverify/$',                     views.ajax_verify_date,               name='dateverify'),
    url(r'^employee_action/$',                views.ContractExtensionView.as_view(),name='employee_action'),
    url(r'^update_session/$',                 views.UpdateSession.as_view(),        name='update_session')

]

handler404 = 'employees.views.pl_404_view'
handler500 = 'employees.views.pl_500_view'

polishlody/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog
from . import views

urlpatterns = [
    url(r'^$', auth_views.login,{'redirect_authenticated_user': True}, name='login'),
    url(r'^accounts/login/$', RedirectView.as_view(url='/')),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^change-password/$', auth_views.password_change, {'template_name': 'registration/change-password.html'}, name='password_change'),
    url(r'^change-password/done/$', auth_views.password_change_done, {'template_name': 'registration/change-password-done.html'}, name='password_change_done'),
    url(r'^resetpassword/passwordsent/$', auth_views.password_reset_done, {'template_name': 'registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^resetpassword/$', auth_views.password_reset, {'template_name': 'registration/password_reset_form.html'}, name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'registration/password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^employees/', include('employees.urls')),
    url(r'^weather/', include('weather.urls')),
    url(r'^sales/', include('sales.urls')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

# urlpatterns += i18n_patterns(
# )

handler404 = 'employees.views.pl_404_view'
handler500 = 'employees.views.pl_500_view'

sales/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',                                views.SalesIndex.as_view(),   name='sales'),
]

employees/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import date
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator
from employees.utils import phone_check, sanity_check, zip_check, is_expiring, is_expiring_contract
from users.models import MyUser


class City(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True, default=None, unique=True)

    class Meta:
        verbose_name = _('city')
        verbose_name_plural = _('cities')

    def __str__(self):
        return self.name


class Employee(MyUser):
    gender_choices = (
        ("Male", _("Male")),
        ("Female", _("Female")),
    )

    position_choices = (
        ("Production", _("Production")),
        ("Sale", _("Sale")),
        ("Other", _("Other")),
    )
    contract_choices = (
        ("Fixed-term employment contract", _("Fixed-term employment contract")),
        ("Non-fixed-term employment contract", _("Non-fixed-term employment contract")),
        ("Contract work", _("Contract work")),  # umowa o dzieło
        ("Fee-for-task contract", _("Fee-for-task contract ")),  # umowa zlecenie
        ("B2B", _("B2B")),
        ("Other", _("Other")),
    )

    rate_per_hour = models.DecimalField(
        _('rate per hour'),
        max_digits=7,
        decimal_places=2,
        blank=True,
        default=0,
        validators=[
            MinValueValidator(0)
        ])

    contract_start_date = models.DateField(
        _('contract start date'),
        blank=True,
        default=timezone.now,
        null=True)  # alter if needed

    contract_exp_date = models.DateField(
        _('contract exp date'),
        blank=True,
        default=None,
        null=True)

    health_book_exp_date = models.DateField(
        _('health book exp date'),
        blank=True,
        default=None,
        null=True)

    gender = models.CharField(
        _('gender'),
        max_length=16,
        blank=False,
        null=True,
        default="Male",
        choices=gender_choices)

    position = models.CharField(
        _('position'),
        max_length=16,
        null=True,
        blank=False,
        default="Other",
        choices=position_choices)

    contract_type = models.CharField(
        _('contract type'),
        blank=True,
        null=True,
        default=None,
        max_length=64,
        choices=contract_choices)

    address_city = models.ForeignKey(
        City,
        to_field='name',
        on_delete=models.SET_NULL,
        max_length=30,
        null=True,
        blank=True,
        verbose_name=_('City'),
        default=None)

    address_street = models.CharField(
        _('Street'),
        max_length=80,
        null=True,
        blank=True,
        default=None)

    address_zip_code = models.CharField(
        _('Zip code'),
        max_length=6,
        blank=True,
        null=True,
        default=None,
        validators=[zip_check])

    bank_account_number = models.CharField(
        _('Bank account number'),
        max_length=250,
        blank=True,
        null=True,
        default=None,
        validators=[sanity_check])

    phone_contact_number = models.CharField(
        _('Phone contact number'),
        max_length=15,
        blank=True,
        null=True,
        default=None,
        validators=[phone_check])

    currently_employed = models.BooleanField(
        _('Currently employed'),
        default=True)

    class Meta:
        verbose_name = _('employee')
        verbose_name_plural = _('employees')

    def months_dict(self):
        months_dict = {1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June',
                       7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'}
        months_enum = list(months_dict.keys())
        return months_dict, months_enum

    def all_unpaid_salaries(self):
        employee_months = self.month_set.all()
        if len(employee_months) != 0:
            unpaid_salaries = 0
            for month in employee_months:
                if month.salary_is_paid is False:
                    ms = month.calculating_salary_for_this_month()
                    unpaid_salaries += ms
            return unpaid_salaries

    def all_unpaid_salaries_for_sorting(self):
        employee_months = self.month_set.all()
        if len(employee_months) != 0:
            unpaid_salaries = 0
            for month in employee_months:
                if month.salary_is_paid is False or month.salary_is_paid == 0:
                    ms = month.calculating_salary_for_this_month()
                    unpaid_salaries += ms
            return unpaid_salaries

    def __str__(self):
        return self.first_name + " " + self.last_name

    def full_name(self):
        return self.last_name + " " + self.first_name

    def is_health_book_expiring(self):
        return is_expiring(self.health_book_exp_date)

    def is_contract_expiring(self):
        return is_expiring_contract(self.contract_exp_date)

    def get_contract_exp_date_string(self):

        if self.contract_exp_date is not None:
            date_to_send = '' + self.contract_exp_date.strftime("%d.%m.%Y")
            return date_to_send
        else:
            return None


class Month(models.Model):
    month_choices = (
        (1, _("January")),
        (2, _("February")),
        (3, _("March")),
        (4, _("April")),
        (5, _("May")),
        (6, _("June")),
        (7, _("July")),
        (8, _("August")),
        (9, _("September")),
        (10, _("October")),
        (11, _("November")),
        (12, _("December")),
    )
    bool_choices = (
        (True, _('Yes')),
        (False, _('No')),
    )
    default_year = date.today().year
    default_month = date.today().month
    months_dict = {1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June',
                   7: 'July', 8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'}

    year = models.PositiveIntegerField(
        _('year'),
        default=default_year,
        validators=[MaxValueValidator(9999)]
    )

    employee = models.ForeignKey(
        Employee,
        null=True,
        blank=True,
        on_delete=models.CASCADE)

    month = models.IntegerField(
        _(u'Month'),
        choices=month_choices,
        default=default_month
    )

    salary_is_paid = models.BooleanField(
        _(u'Paid?'),
        default=False,
        choices=bool_choices
    )

    hours_worked_in_this_month = models.DecimalField(
        _('hours worked in this month'),
        decimal_places=1,
        max_digits=4,
        default=0,
        validators=[MaxValueValidator(720), MinValueValidator(0)]
    )

    month_is_approved = models.BooleanField(
        _(u'Approved?'),
        default=False,
        choices=bool_choices
    )

    month_not_approved_with_comment = models.BooleanField(
        _(u'Approved?'),
        default=False,
        choices=bool_choices
    )

    message_reason_hours_not_approved = models.TextField(
        _('Comment, why you disagree with the hours (optional)'),
        blank=True,
        null=True,
        default=None
    )

    rate_per_hour_this_month = models.DecimalField(
        _('rate per hour this month'),
        decimal_places=2,
        max_digits=7,
        default=0,
        validators=[MinValueValidator(0)]
    )

    bonuses = models.DecimalField(
        _('Bonuses'),
        decimal_places=2,
        max_digits=7,
        default=0,
        validators=[MinValueValidator(0)]
    )

    def __str__(self):
        return self.months_dict[self.month] + " " + str(self.year)

    def month_status(self):
        if self.salary_is_paid == False:
            return str(self.month) + " " + str(self.year) + " - " + str(self.employee) + " - Not paid yet."
        if self.salary_is_paid == True:
            return str(self.month) + " " + str(self.year) + " - " + str(self.employee) + " - Paid!"

    def month_detail(self):
        return str(self.year) + " " + self.months_dict[int(self.month)]

    def simple_month_name(self):
        return str(self.month)

    def month_name(self):
        return self.months_dict[self.month]

    def calculating_salary_for_this_month(self):
        return round((self.rate_per_hour_this_month * self.hours_worked_in_this_month + self.bonuses), 2)

    class Meta:
        verbose_name = _('month')
        verbose_name_plural = _('months')
        unique_together = (("employee", "month", "year"),)

templates/employees/employee_confirm_delete.html
{% extends 'polishlody/base.html' %}
{% load i18n %}

{% block title %}{% trans 'Confirmation' %}{% endblock %}
        
{% block body_block %}

    <div class="panel panel-heading panel-danger">
        <center>
            <div>
                <h4>{% trans 'Confirmation' %}</h4>
            </div>
            <div class="panel-danger">
                <form method="post">
                    {% csrf_token %}
                    {% trans 'Are you sure you want to delete employee ' %}{{ object.full_name }}?<br>
                    <p class="warning">
                        {% trans 'This is irreversible! Employee data will be lost forever.' %}
                    </p>
                    <br>
                    <input type="submit" name="submit" value="{% trans 'Yes' %}" class="btn btn-danger">
                    <a href="{% url 'employees' %}" class="btn btn-default">{% trans 'Back to the employee list' %}</a>
                </form>
            </div>
        </center>
    </div>

{% endblock %}

templates/employees/employee_message.html
{% extends 'polishlody/base.html' %}
{% load i18n %}


<div class="panel panel-heading panel-default">
    <div class="form-container approval-container"> 

            <h4>message from employee</h4>

    </div>
</div>

templates/employees/month_NOT_approve.html
{% extends 'polishlody/base.html' %}
{% load i18n %}

{% block body_block %}

<head>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

</head>
<div class="panel panel-heading panel-default">
    <div class="form-container approval-container">

        <center>
            <h4>
                {% trans 'Are you sure you want to disapprove this month?' %}
            </h4>
            <table class="table table-hover approval-table">
                <tr>
                    <td>
                        {% trans 'Employee:' %}
                    </td>
                    <td>
                        {{ employee.employee }}
                    </td>
                <tr>
                    <td>
                        {% trans 'Month:' %}
                    </td>
                    <td>
                        {{ month.get_month_display }} {{ month.year }}
                    </td>
                </tr>

                <tr>
                    <td>
                        {% trans 'Hours worked in this month:' %}
                    </td>
                    <td>
                        {{ month.hours_worked_in_this_month }}
                    </td>
                </tr>
                <tr>
                    <td>
                        {% trans 'Rate per hour this month:' %}
                    </td>
                    <td>
                        {{ month.rate_per_hour_this_month }}
                    </td>
                </tr>
            </table>
        </center>

        <div id="chars_remaning_id" name= "{% trans 'Characters remaining' %}"  align="center">{% trans 'Characters remaining' %} 1000</div>

        <form method="POST">

            <textarea class="form-container textarea_disapprove" name="employee_message" id="employee_message_id" maxlength=1000 placeholder="Your message"></textarea>


            {% csrf_token %}
            <center>
                <input type="submit" name="submit" value="{% trans 'Submit' %}" class="btn btn-primary">
                <a href="{% url 'employee_detail' employee.id %}" class="btn btn-danger">{% trans 'Cancel' %}</a>
                {{ form.month_not_approved_with_comment }}

            </center>
        </form>

    </div>


</div>

<script>

       $('#employee_message_id').on('keyup', function(){
       let charsRemaningArea=$('#chars_remaning_id');
       let remanings=1000-(+$(this).val().length);
       charsRemaningArea.text(charsRemaningArea.attr('name')+" "+ remanings);
    });


</script>
{% endblock %}

templates/employees/month_approve.html
{% extends 'polishlody/base.html' %}
{% load i18n %}

{% block body_block %}
<div class="panel panel-heading panel-default">
    <div class="form-container approval-container"> 
        <center>
            <h4>
                {% trans 'Are you sure you want to approve this month?' %}
            </h4>                 
            <table class="table table-hover approval-table">
                <tr>
                    <td>
                        {% trans 'Employee:' %}
                    </td> 
                    <td>
                        {{ employee.employee }}
                    </td>
                <tr>
                    <td>
                        {% trans 'Month:' %}
                    </td>
                    <td>
                       {{ month.get_month_display }} {{ month.year }}
                    </td>
                </tr>

                <tr>  
                    <td>
                        {% trans 'Hours worked in this month:' %}
                    </td>
                <td>
                    {{ month.hours_worked_in_this_month }}
                </td>
                </tr>
                <tr>
                    <td>
                        {% trans 'Rate per hour this month:' %}
                    </td>
                    <td>
                        {{ month.rate_per_hour_this_month }}
                    </td>
                </tr>
            </table>
        </center>
        <form method="POST">
        {% csrf_token %}
            <center>
                <input type="submit" name="submit" value="{% trans 'Submit' %}" class="btn btn-primary">
                <a href="{% url 'employee_detail' employee.id %}" class="btn btn-danger">{% trans 'Cancel' %}</a>
                {{ form.month_is_approved }}
            </center>
        </form>
    </div>
</div>
{% endblock %}

templates/employees/month_confirm_delete.html
{% extends 'polishlody/base.html' %}
{% load i18n %}

{% block title %}
{% if month %}{% trans 'Confirmation' %}
{% else %} 404
{% endif %}
{% endblock %}
        
{% block body_block %}

    {% if month %}
    <div class="panel panel-heading panel-danger">
        <center>
            <div>
                <h4>{% trans 'Confirmation' %}</h4>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    {% trans 'Are you sure you want to delete' %} {{ object.get_month_display }} {{ object.year }}?<br>
                    <p class="warning">
                        {% trans 'Any data related to this month will be lost forever.' %}
                    </p>
                    <br>
                    {% if employee %}
                    <a href="{% url 'employee_detail' employee.id %}"><input type="submit" name="submit" value="{% trans 'Yes' %}" class="btn btn-danger"></a>
                    <a href="{% url 'employee_detail' employee.id %}" class="btn btn-default">{% trans 'No, take me back to the employee detail' %}</a>
                    {% endif %}
                </form>
            </div>
            </div>
            {% else %}
            <div class="panel panel-danger">
            <div class="panel-body">
                <p>{% trans 'The month you are trying to delete does not exist anymore.' %}</p>
                <a href="{% url 'employees' %}" class="btn btn-default">{% trans 'Back to the employee list' %}</a>
            </div>
        </center>
    </div>

    {% endif %}

{% endblock %}

templates/employees/month_edit_form.html
{% extends 'polishlody/base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% block title %}
{% if month %}{% trans 'Editing month' %} {{ month.get_month_display }} {{ month.year }}
{% else %}404
{% endif %}
{% endblock %}

{% block header_block %}
{% if month %}
<div class="panel panel-heading panel-default">
    <center>
        <h4>
            {% if employee and month %}
            {% trans 'Editing' %} {{ month.get_month_display }} {{ month.year }} {% trans 'for' %} {{ employee }}
            {% endif %}
        </h4>
    </center>
</div>
{% endif %}
{% endblock %}
{% block body_block %}
<a href="{% url 'employee_detail' employee.id %}" class="btn btn-default">{% trans 'Back' %}</a>
{% if month %}
    <div class="panel panel-heading panel-default">
        <div class="form-container">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">
                    <form method="post" class="form-horizontal" id="monthform">
                        {% csrf_token %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                        {% endfor %}
                        {% if form.errors %}
                            <div class="alert alert-danger" role="alert">
                            {% for e in form %}
                                {{e.errors|escape}}
                            {% endfor %}
                            </div>
                        {% endif %}
                        {% for e in form %}
                        {% if e.label == "Employee" %}
                            <div class="form-group" hidden>
                                <label class="col-sm-4 control-label">{{ e.label }}</label>
                                <div class="col-sm-4">
                                    {{ e|add_class:"form-control" }}
                                </div>
                            </div>
                        {% elif e.html_name == "hours_worked_in_this_month" %}
                            <div class="form-group">
                                <label class="col-sm-4 control-label">{% trans 'Hours worked:' %}</label>
                                <div class="col-sm-4">
                                    {{ e|add_class:"form-control" }}
                                </div>
                            </div>
                        {% elif e.html_name == "rate_per_hour_this_month" %}
                            <div class="form-group">
                                <label class="col-sm-4 control-label">{% trans 'Rate per hour:' %}</label>
                                <div class="col-sm-4 form-field">
                                    {{ e|add_class:"form-control" }}
                                </div>
                            </div>
                        {% elif e.html_name == "salary_is_paid" %}
                            <div class="form-group">
                                <label class="col-sm-4 control-label">{{ e.label }}</label>
                                <div class="col-sm-4 radio-select">
                                    {{ e }}
                                </div>
                            </div>
                        {% else %}
                        <div class="form-group">
                                <label class="col-sm-4 control-label">{{ e.label }}:</label>
                                <div class="col-sm-4 form-field">
                                    {{ e|add_class:"form-control" }}
                                </div>
                            </div>
                        {% endif %}
                        {% endfor %}
                        <br>
                        <center>
                            <input type="submit" name="submit" value="{% trans 'Submit' %}" class="btn btn-primary">
                            <a href="{% url 'employee_detail' employee.id %}" class="btn btn-default">{% trans 'Cancel' %}</a>
                        </center>
                        <br>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script><!-- javascript strings translations -->
    <script>
        function getPk() {
            var employeeID= {{ employee.pk }}
            return employeeID
        }

        function resetmontform() {
            document.getElementById('monthform').reset();
        }
        resetmontform();
        var yearinit = $('#id_year').val();
        var monthinit = $('#id_month').val();
    </script>
{% else %}

    <div class="panel panel-danger">
        <div class="panel-body">
            <p>The month you are trying to edit does not exist anymore.</p>
            <a href="{% url 'employees' %}" class="btn btn-default">Back to the employee list</a>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/employees/month_form.html
{% extends 'polishlody/base.html' %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% trans 'Create new month' %}{% endblock %}
{% block header_block %}
    <div class="panel panel-heading panel-default">
        <center>
            <h4>
                {% if employee %}
                {% trans 'New month for' %} {{ employee }}
                {% endif %}
            </h4>
        </center>
    </div>
{% endblock %}
{% block body_block %}
<a href="{% url 'employee_detail' employee.id %}" class="btn btn-default">{% trans 'Back' %}</a>
    <div class="panel panel-heading panel-default">
        <div class="form-container">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">
                    <form method="post" class="form-horizontal" id="monthform">
                        {% csrf_token %}
                        {% if form.hours_worked_in_this_month.errors or form.rate_per_hour_this_month.errors or form.bonuses.errors %}
                            <div class="alert alert-danger" role="alert">
                            {% for e in form %}
                                {{e.errors|escape}}
                            {% endfor %}
                            </div>
                        {% endif %}
                        {% for e in form %}
                        {% if e.label == "Employee" %}
                            <div class="form-group" hidden>
                                <label class="col-sm-4 control-label">{{ e.label }}</label>
                                <div class="col-sm-4">
                                    {{ e|add_class:"form-control" }}
                                </div>
                            </div>
                        {% elif e.html_name == "hours_worked_in_this_month" %}
                            <div class="form-group">
                                <label class="col-sm-4 control-label">{% trans 'Hours worked:' %}</label>
                                <div class="col-sm-4">
                                    {{ e|add_class:"form-control" }}
                                </div>
                            </div>
                        {% elif e.html_name == "rate_per_hour_this_month" %}
                            <div class="form-group">
                                <label class="col-sm-4 control-label">{% trans 'Rate per hour:' %}</label>
                                <div class="col-sm-4 form-field">
                                    {{ e|add_class:"form-control" }}
                                </div>
                            </div>
                        {% elif e.html_name == "salary_is_paid" %}
                            <div class="form-group">
                                <label class="col-sm-4 control-label">{{ e.label }}</label>
                                <div class="col-sm-4 radio-select">
                                    {{ e }}
                                </div>
                            </div>
                        {% else %}
                        <div class="form-group">
                                <label class="col-sm-4 control-label">{{ e.label }}:</label>
                                <div class="col-sm-4 form-field">
                                    {{ e|add_class:"form-control" }}
                                </div>
                            </div>
                        {% endif %}
                        {% endfor %}
                        <br>
                        <center>
                            <input type="submit" name="submit" value="{% trans 'Submit' %}" class="btn btn-primary" />

                            <a href="{% url 'employee_detail' employee.id %}" class="btn btn-default">{% trans 'Cancel' %}</a>
                        </center>
                        <br>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script><!-- javascript strings translations -->
    <script>
        function getPk() {
            var employeeID= {{ employee.pk }}
            return employeeID
        }

        function resetmontform() { //function to reset form after site reload
            document.getElementById('monthform').reset();
        }
        resetmontform();
        var yearinit = null;
        var monthinit = null;
    </script>
{% endblock %}